### ISSUE TITLE
Add fork me and deploy me buttons

### ISSUE THREAD

**Issue by thisismydesign** [c-hive/dotdev#109]
Fork me is a github button
Deploy me is a heroku button 
Try to find a button for github pages

**Comment by gomorizsolt** [comment]
I'd also add options for well-known hosting services if possible:
- https://vercel.com/
- https://www.netlify.com/

![CleanShot 2020-05-12 at 19 02 51](https://user-images.githubusercontent.com/30864202/81723508-38099480-9483-11ea-86c8-1f108e3a58f0.png)

**Comment by thisismydesign** [comment]
Looks a bit marketing-y to me.

**Comment by gomorizsolt** [comment]
> Looks a bit marketing-y to me.

What do you mean by "marketing-y"? They're too specific deployment services?

**Comment by thisismydesign** [comment]
Yes, I'd say GH Pages and Heroku are the "go-to" vendors for this use case but these are less known.

**Comment by gomorizsolt** [comment]
Gotcha. By the way, they're not less known services. In fact, Next.js [recommends](https://nextjs.org/docs/deployment#vercel-recommended) using their own platform for deployments.

**Comment by thisismydesign** [comment]
As a compromise: https://github.com/c-hive/dotdev/commit/7ce17f1ffb662fadd4234b9048832d1c45d1aa04

I'd consider this done.
